# Generated by Django 4.2.3 on 2023-07-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_biometrics_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometrics',
            name='heartBeatVar',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='biometrics',
            name='respiratoryRate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='biometrics',
            name='restingHeartRate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='biometrics',
            name='date',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='biometrics',
            name='heartBeat',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
