# Generated by Django 4.2.3 on 2023-08-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_alter_biometrics_heartbeat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometrics',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
