# Generated by Django 4.2.3 on 2023-08-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_alter_biometrics_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometrics',
            name='arousal',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='biometrics',
            name='valence',
            field=models.FloatField(default=None, null=True),
        ),
    ]
