# Generated by Django 4.2.3 on 2023-08-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_biometrics_arousal_biometrics_valence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('biometricData', models.ManyToManyField(blank=True, null=True, to='collect.biometrics')),
            ],
        ),
        migrations.AddField(
            model_name='biometrics',
            name='watchID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='collect.users'),
        ),
    ]
