# Generated by Django 4.2.3 on 2023-08-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0007_users_biometrics_watchid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biometrics',
            old_name='watchID',
            new_name='watchUser',
        ),
    ]
