# Generated by Django 4.2.3 on 2023-08-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0008_rename_watchid_biometrics_watchuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometrics',
            name='watchUser',
        ),
        migrations.AddField(
            model_name='biometrics',
            name='watchID',
            field=models.CharField(default='', max_length=30),
        ),
    ]
