# Generated by Django 4.2.3 on 2023-08-08 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0009_remove_biometrics_watchuser_biometrics_watchid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometrics',
            name='watchID',
        ),
        migrations.AddField(
            model_name='biometrics',
            name='watchUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='collect.users'),
        ),
    ]
