# Generated by Django 4.2.3 on 2023-08-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0010_remove_biometrics_watchid_biometrics_watchuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometrics',
            name='activity',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
